#!/bin/bash
### BEGIN INIT INFO
# Provides:
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# init-script adapted from https://github.com/fhd/init-script-template

dir="/usr/sbin"
cmd="incrond"
user=""

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    [ -r "$pid_file" ] && cat "$pid_file"
}

is_running() {
    [ -r $pid_file ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running ; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [[ -z "$user" ]]; then
            $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        $0 status
    fi
    ;;
    stop)
    if is_running ; then
        echo -n "Stopping $name.."
        kill `get_pid`
        if is_running ; then 
          for i in 1 2 3 4 5 6 7 8 9 10; do
            if  ! is_running ; then
                break
            fi

            echo -n "."
            sleep 1
          done
        fi
        echo

        if is_running ; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [[ -f "$pid_file" ]]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running ; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running ; then
        PID=`get_pid`
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
